apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  namespace: webproject
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    name: webapp
    namespace: webproject
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: image-registry.openshift-image-registry.svc:5000/webproject/webapp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: 50Mi
            cpu: 200m
          limits:
            memory: 80Mi
            cpu: 500m
        env:
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: mariadb-credential
              key: username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-credential
              key: password
        - name: DATABASE_INSTANCE_NAME
          valueFrom:
            configMapKeyRef:
              name: database-configmap
              key: database_instance
        - name: DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: database-configmap
              key: database
      restartPolicy: Always


