kind: Pod
apiVersion: v1
metadata:
  generateName: webapp-name-1-
  annotations:
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "openshift-sdn",
          "interface": "eth0",
          "ips": [
              "10.128.2.143"
          ],
          "dns": {},
          "default-route": [
              "10.128.2.1"
          ]
      }]
    kubernetes.io/limit-ranger: >-
      LimitRanger plugin set: cpu, memory request for container webapp-name;
      cpu, memory limit for container webapp-name
    openshift.io/deployment-config.latest-version: '1'
    openshift.io/deployment-config.name: webapp-name
    openshift.io/deployment.name: webapp-name-1
    openshift.io/scc: restricted
  selfLink: /api/v1/namespaces/webproject/pods/webapp-name-1-grjht
  resourceVersion: '289272833'
  name: webapp-name-1-grjht
  uid: e6b7016a-d314-4df3-bb0a-ce4383eaf68c
  creationTimestamp: '2020-10-08T13:25:25Z'
  namespace: webproject
  ownerReferences:
    - apiVersion: v1
      kind: ReplicationController
      name: webapp-name-1
      uid: b5a3e9b0-7a39-407d-a001-8ed41e0a6681
      controller: true
      blockOwnerDeletion: true
  labels:
    app: webapp-name
    deployment: webapp-name-1
    deploymentconfig: webapp-name
spec:
  restartPolicy: Always
  serviceAccountName: default
  imagePullSecrets:
    - name: default-dockercfg-w8h6g
  priority: 0
  schedulerName: default-scheduler
  enableServiceLinks: true
  terminationGracePeriodSeconds: 30
  nodeName: ip-10-0-156-14.us-west-2.compute.internal
  securityContext:
    seLinuxOptions:
      level: 's0:c79,c59'
    fsGroup: 1006280000
  containers:
    - name: webapp-name
      image: >-
        image-registry.openshift-image-registry.svc:5000/webproject/webapp-name@sha256:d8e7b211926530a360d5e2d5839b1dafb86d42c82c4b9836173185509033419b
      resources:
        limits:
          cpu: 500m
          memory: 1536Mi
        requests:
          cpu: 50m
          memory: 256Mi
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mariadb
              key: database-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb
              key: database-password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mariadb
              key: database-name
      volumeMounts:
        - name: default-token-6fnns
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: Always
      securityContext:
        capabilities:
          drop:
            - KILL
            - MKNOD
            - SETGID
            - SETUID
        runAsUser: 1006280000
  serviceAccount: default
  volumes:
    - name: default-token-6fnns
      secret:
        secretName: default-token-6fnns
        defaultMode: 420
  dnsPolicy: ClusterFirst
  tolerations:
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/memory-pressure
      operator: Exists
      effect: NoSchedule
