kind: Pod
apiVersion: v1
metadata:
  generateName: mariadb-1-
  annotations:
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "openshift-sdn",
          "interface": "eth0",
          "ips": [
              "10.129.9.162"
          ],
          "dns": {},
          "default-route": [
              "10.129.8.1"
          ]
      }]
    kubernetes.io/limit-ranger: >-
      LimitRanger plugin set: cpu request for container mariadb; cpu limit for
      container mariadb
    openshift.io/deployment-config.latest-version: '1'
    openshift.io/deployment-config.name: mariadb
    openshift.io/deployment.name: mariadb-1
    openshift.io/scc: restricted
  selfLink: /api/v1/namespaces/webproject/pods/mariadb-1-sts66
  resourceVersion: '299594760'
  name: mariadb-1-sts66
  uid: baaeaa4f-b515-45e9-b755-8613056a4dba
  creationTimestamp: '2020-10-13T07:28:08Z'
  namespace: webproject
  ownerReferences:
    - apiVersion: v1
      kind: ReplicationController
      name: mariadb-1
      uid: 2b097c3c-fb31-4404-bfdc-beec0f7cfff5
      controller: true
      blockOwnerDeletion: true
  labels:
    deployment: mariadb-1
    deploymentconfig: mariadb
    name: mariadb
spec:
  restartPolicy: Always
  serviceAccountName: default
  imagePullSecrets:
    - name: default-dockercfg-952d5
  priority: 0
  schedulerName: default-scheduler
  enableServiceLinks: true
  terminationGracePeriodSeconds: 30
  nodeName: ip-10-0-157-94.us-west-2.compute.internal
  securityContext:
    seLinuxOptions:
      level: 's0:c59,c39'
    fsGroup: 1003500000
  containers:
    - resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 50m
          memory: 512Mi
      readinessProbe:
        exec:
          command:
            - /bin/sh
            - '-i'
            - '-c'
            - >-
              MYSQL_PWD="$MYSQL_PASSWORD" mysql -h 127.0.0.1 -u $MYSQL_USER -D
              $MYSQL_DATABASE -e 'SELECT 1'
        initialDelaySeconds: 5
        timeoutSeconds: 1
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 3
      terminationMessagePath: /dev/termination-log
      name: mariadb
      livenessProbe:
        tcpSocket:
          port: 3306
        initialDelaySeconds: 30
        timeoutSeconds: 1
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 3
      env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mariadb
              key: database-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb
              key: database-password
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb
              key: database-root-password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mariadb
              key: database-name
      securityContext:
        capabilities:
          drop:
            - KILL
            - MKNOD
            - SETGID
            - SETUID
        runAsUser: 1003500000
      ports:
        - containerPort: 3306
          protocol: TCP
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: mariadb-data
          mountPath: /var/lib/mysql/data
        - name: default-token-99x9x
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePolicy: File
      image: >-
        image-registry.openshift-image-registry.svc:5000/openshift/mariadb@sha256:ad16d811025295daba76402740ca0d126983161406b0901b623a7112b8997601
  serviceAccount: default
  volumes:
    - name: mariadb-data
      persistentVolumeClaim:
        claimName: mariadb
    - name: default-token-99x9x
      secret:
        secretName: default-token-99x9x
        defaultMode: 420
  dnsPolicy: ClusterFirst
  tolerations:
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/memory-pressure
      operator: Exists
      effect: NoSchedule
status:
  phase: Running
  conditions:
    - type: Initialized
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2020-10-13T07:28:08Z'
    - type: Ready
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2020-10-13T07:28:38Z'
    - type: ContainersReady
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2020-10-13T07:28:38Z'
    - type: PodScheduled
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2020-10-13T07:28:08Z'
  hostIP: 10.0.157.94
  podIP: 10.129.9.162
  podIPs:
    - ip: 10.129.9.162
  startTime: '2020-10-13T07:28:08Z'
  containerStatuses:
    - restartCount: 0
      started: true
      ready: true
      name: mariadb
      state:
        running:
          startedAt: '2020-10-13T07:28:22Z'
      imageID: >-
        image-registry.openshift-image-registry.svc:5000/openshift/mariadb@sha256:ad16d811025295daba76402740ca0d126983161406b0901b623a7112b8997601
      image: >-
        image-registry.openshift-image-registry.svc:5000/openshift/mariadb@sha256:ad16d811025295daba76402740ca0d126983161406b0901b623a7112b8997601
      lastState: {}
      containerID: 'cri-o://fdf511cc1308af493ce6dee2e0b704ea4481a8789092aeb6b56b9018c9e13859'
  qosClass: Burstable
