kind: Project
apiVersion: project.openshift.io/v1
metadata:
  name: webproject
  selfLink: /apis/project.openshift.io/v1/projects/webproject
  uid: 8771e77d-46f9-48fe-9c5b-332d4458bcbb
  resourceVersion: '299588016'
  creationTimestamp: '2020-10-13T07:24:25Z'
  annotations:
    openshift.io/description: ''
    openshift.io/display-name: ''
    openshift.io/requester: sakhawat.ali-northbaysolutions.n
    openshift.io/sa.scc.mcs: 's0:c59,c39'
    openshift.io/sa.scc.supplemental-groups: 1003500000/10000
    openshift.io/sa.scc.uid-range: 1003500000/10000
spec:
  finalizers:
    - kubernetes
status:
  phase: Active
